# Generated by Django 4.1 on 2022-09-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesores', '0003_remove_colegio_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('procedencia', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Colegio',
        ),
    ]
